if: (type = push AND branch = master) OR (type = pull_request AND branch = master)

language: node_js
node_js:
  - 12
cache:
  directories:
  - node_modules
script:
  - yarn install
  - yarn build-storybook
  - yarn build-dev
